version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 753863853239.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo "Building the Maven project..."
      - mvn clean package
      - cp target/livedemo.war .
      - echo Building the Docker image...
      - docker build -t code-pipeline-ecr .
      - docker tag code-pipeline-ecr:latest 753863853239.dkr.ecr.us-east-1.amazonaws.com/code-pipeline-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 753863853239.dkr.ecr.us-east-1.amazonaws.com/code-pipeline-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"code-pipeline-ecr","imageUri":"%s"}]' 753863853239.dkr.ecr.us-east-1.amazonaws.com/code-pipeline-ecr:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
